function Hd = ButterworthBandpass
%BUTTERWORTHBANDPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 08-Apr-2021 04:41:08

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in kHz.
Fs = 100;  % Sampling Frequency

Fstop1 = 25;          % First Stopband Frequency
Fpass1 = 30;          % First Passband Frequency
Fpass2 = 40;          % Second Passband Frequency
Fstop2 = 45;          % Second Stopband Frequency
Astop1 = 50;          % First Stopband Attenuation (dB)
Apass  = 5;           % Passband Ripple (dB)
Astop2 = 50;          % Second Stopband Attenuation (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
